name: TemporaryProtections
main: com.xiluiis.temporaryprotections.TemporaryProtections
author: xShadowsystem
description: Plugin para gestionar protecciones temporales en eventos de Minecraft
version: 1.0.1-beta
api-version: 1.20
depend: [WorldGuard]
commands:
  tmpp:
    description: Maneja informacion sobre protecciones temporales
    usage: /tmpp help