name: TemporaryProtections
main: com.xiluiis.temporaryprotections.TemporaryProtections
author: xShadowsystem
description: Plugin para gestionar protecciones temporales en eventos de Minecraft
version: 1.0
api-version: 1.20
depend: [WorldGuard]
commands:
  tp:
    description: Activa o desactiva el modo de eventos
    usage: /tmpp events yes|no